### ISSUE TITLE
[PE-D][Tester B] Error updating any user settings

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-1/tp#128]
![image.png](https://raw.githubusercontent.com/Brennanzuz/ped/main/files/8299108b-0010-47f2-9c8c-f85fa7c87e4a.png)

It is impossible to change the user name and profile.

Steps to replicate:
1. Start program
2. Type `update`
3. Type `1`
4. Type any name, for example `Akshay`
5. Error "`Cannot invoke "seedu.entities.User.setName(String)" because "user" is null`" is thrown

As a result, most features in the `view` and `update` commands simply cannot work as it throws the same error.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Brennanzuz/ped#1

**Comment by MingEn82** [comment]
Fixed by creating user file properly
