### ISSUE TITLE
[PE-D][Tester C] Application outputs "null" instead of "success" or "failure" message

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-1/tp#145]
![image.png](https://raw.githubusercontent.com/lohjooh/ped/main/files/d2e93e49-94bc-43ad-adb2-4ec22aa8a099.png)

After user inputs `update` and any integer from `1` to `5`, "null" is output from the application with no message indicating if the entry was saved successfully or not.

Expected: Application to output a "success" message for successful saving of fields, and "failure" message for failure to save the field.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lohjooh/ped#8

**Comment by MingEn82** [comment]
Fixed by creating user file properly
