### ISSUE TITLE
[PE-D][Tester D] Unable to Add certain foods from list of foods

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-1/tp#155]
There are certain foods that I am unable to add, even though they appear in the list.
e.g.
![image.png](https://raw.githubusercontent.com/sriram-senthilkr/ped/main/files/5bbaa965-1ed5-4c70-95a4-29770cabdb9d.png)

list:
![image.png](https://raw.githubusercontent.com/sriram-senthilkr/ped/main/files/417a9479-5c10-4b09-9e80-9cb88b2ba477.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: sriram-senthilkr/ped#6

**Comment by MingEn82** [comment]
There is some issue with the filter function. I'll check it out

**Comment by MingEn82** [comment]
Fixed bug with filter function
