### ISSUE TITLE
[PE-D][Tester D] Redundant repetition of meals in list meals command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-1/tp#159]
Lunch and Dinner was repeated, with no data in Dinner, even though it was for the same day when `list meals` command was entered.

![image.png](https://raw.githubusercontent.com/sriram-senthilkr/ped/main/files/0bad7ea9-52f0-48be-be72-80c2db757031.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: sriram-senthilkr/ped#8

**Comment by MingEn82** [comment]
Can't replicate this bug. Not sure what is going on
