### ISSUE TITLE
[PE-D][Tester B] `filter` does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W15-1/tp#160]
![image.png](https://raw.githubusercontent.com/Brennanzuz/ped/main/files/018dda37-2946-4bf6-af46-9c2ec1a32794.png)

`filter` will always throw "`Please enter valid lower and upper limits!`" even if the user inputs valid calories, as shown by `Creamy Chicken Spaghetti (Small)` having 755.0 calories and `Prawns & Mushroom Spaghetti (Small)` having 557.0 calories.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Brennanzuz/ped#7

**Comment by MingEn82** [comment]
Fixed
