### ISSUE TITLE
[PE-D][Tester D] Filter feature unable to filter food

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W15-1/tp#162]
I entering a food (e.g. egg in this case), which came out to have 256.0 calories. Then, i tried filtering it, but was unable to do so. I tried 2 digit float number, 1 digit float number, and finally an integer, but none of them seemed to work.

![image.png](https://raw.githubusercontent.com/sriram-senthilkr/ped/main/files/9e9e5e92-4a2f-4592-8df9-cd340b6334a3.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: sriram-senthilkr/ped#9

**Comment by MingEn82** [comment]
Fixed
